# Prover parameters (single source of truth for proof generation)
# Sync to noir_circuit: pnpm run sync-prover-params

root = "0x0b5396cd78e7d0fb124fded66bf0acfb027d4d6817003874a9f05bd43049f5af"
nullifier = "0x15885aac6f86690b97fccf3720bd37d239d980b98303051f8f8e9562223df985"
recipient = "0x000055eafde7cf70b24e3e643a46fe9cb933488c26977a31292ff009bec2d712"
amount = 10000000
wa_commitment = "0x114321a93a82c81955d8587c6f129db82f5dcd3d2d46216297dc8514d8886dc0"
secret_key = "0x0000000000000000000000000000000043f5147fe5a665df7600da3ae1c0ae1c"
owner_x = "0x13c1a5d58f3ce2659c8cb9f6686264197864954b53a3ba1eda4168b9b18927b8"
owner_y = "0x1d1e2a6a28d810bc04992f6e8f890f1d9cad471819bc111ae229b507f4d77a0f"
randomness = "0x0012edb4c51b50c903f5c6c8fb1e1f5ee5a398339639212f57f15fd0c05e166a"
index = 0
siblings = [
  "0x0000000000000000000000000000000000000000000000000000000000000000",
  "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864",
  "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1",
  "0x18f43331537ee2af2e3d758d50f72106467c6eea50371dd528d57eb2b856d238",
  "0x07f9d837cb17b0d36320ffe93ba52345f1b728571a568265caac97559dbc952a",
  "0x2b94cf5e8746b3f5c9631f4c5df32907a699c58c94b2ad4d7b5cec1639183f55",
  "0x2dee93c5a666459646ea7d22cca9e1bcfed71e6951b953611d11dda32ea09d78",
  "0x078295e5a22b84e982cf601eb639597b8b0515a88cb5ac7fa8a4aabe3c87349d",
  "0x2fa5e5f18f6027a6501bec864564472a616b2e274a41211a444cbe3a99f3cc61",
  "0x0e884376d0d8fd21ecb780389e941f66e45e7acce3e228ab3e2156a614fcd747",
  "0x1b7201da72494f1e28717ad1a52eb469f95892f957713533de6175e5da190af2",
  "0x1f8d8822725e36385200c0b201249819a6e6e1e4650808b5bebc6bface7d7636",
  "0x2c5d82f66c914bafb9701589ba8cfcfb6162b0a12acf88a8d0879a0471b5f85a",
  "0x14c54148a0940bb820957f5adf3fa1134ef5c4aaa113f4646458f270e0bfbfd0",
  "0x190d33b12f986f961e10c0ee44d8b9af11be25588cad89d416118e4bf4ebe80c",
  "0x22f98aa9ce704152ac17354914ad73ed1167ae6596af510aa5b3649325e06c92",
]
